#!/usr/bin/env bash
#
# sync-windows.sh — mirror the platform independent files of the dart projects
# to their windows copies on the mounted windows partition.
#
# Development is done under linux, while the same projects are built under
# windows from their own copy. This script copies what the two sides share —
# the dart sources, the assets, the electron shell, the docs and the pubspec —
# and leaves out what each side has to keep for itself:
#
#   - the platform projects ( android, ios, linux, macos, windows ), both of
#     the project itself and of the example app of base
#   - the files generated by the dart / flutter tooling ( build, .dart_tool,
#     pubspec.lock ) and .flutter-plugins*, which even hold absolute paths
#     into the local pub cache
#   - the version control and the IDE settings ( .git, .idea, .vscode, *.iml )
#   - the distribution payloads ( dist/vendor, dist/out ) and the vcpkg
#     submodule under dist/scripts, a windows build toolchain of it's own
#
# The platform folders inside dist/templates are NOT excluded: they are the
# templates the distribution is assembled from, so they belong to the sources.
#
# Nothing is deleted on the windows side by default, see --delete.
#
# Usage:
#   tools/sync-windows.sh [options] [project ...]
#
# Options:
#   --dest <dir>   The windows workspace root
#                  (default: /run/media/mk/OS/workspace)
#   --delete       Also delete the files on the windows side that are gone
#                  here. Off by default: the windows copies hold files of
#                  their own ( old archives, pdf manuals ), which would be
#                  deleted as well. Combine with --dry-run first.
#   -n, --dry-run  List what would be copied, change nothing
#   -h, --help     Show this help
#
# Projects: base, scriptscreen   (default: both)
#
set -euo pipefail

SRC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEST_ROOT="/run/media/mk/OS/workspace"
ALL_PROJECTS=( base scriptscreen )
DRY_RUN=0
DELETE=0
PROJECTS=( )

die() { echo "error: $*" >&2; exit 1; }
log() { echo "==> $*"; }

while [ $# -gt 0 ]; do
    case "$1" in
        --dest)       DEST_ROOT="${2:-}"; shift 2;;
        --delete)     DELETE=1; shift;;
        -n|--dry-run) DRY_RUN=1; shift;;
        -h|--help)    sed -n '2,38p' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
        -*)           die "unknown argument: $1";;
        *)            PROJECTS+=( "$1" ); shift;;
    esac
done

if [ ${#PROJECTS[@]} -eq 0 ]; then
    PROJECTS=( "${ALL_PROJECTS[@]}" )
fi

for project in "${PROJECTS[@]}"; do
    case " ${ALL_PROJECTS[*]} " in
        *" $project "*) ;;
        *) die "unknown project: $project (known: ${ALL_PROJECTS[*]})";;
    esac
done

# Patterns without a leading slash match at any depth, the anchored ones only
# at the root of the project being synced.
EXCLUDES=(
    # version control and IDE settings
    '.git/' '.idea/' '.vscode/' '.history/' '*.iml'
    # generated by the dart / flutter tooling, belongs to the machine
    '.dart_tool/' 'build/' '.packages' 'pubspec.lock'
    # hold absolute paths into the local pub cache
    '.flutter-plugins' '.flutter-plugins-dependencies'
    # the platform projects, each side keeps it's own
    '/android/' '/ios/' '/linux/' '/macos/' '/windows/'
    '/example/android/' '/example/ios/' '/example/linux/' '/example/macos/' '/example/windows/'
    # distribution payloads and the vcpkg toolchain submodule
    '/dist/vendor/' '/dist/out/' '/dist/scripts/vcpkg/'
    # leftovers
    '*.log' '*.swp' '.DS_Store'
)

# The destination is ntfs mounted through fuse: the permissions, the owner and
# the group cannot be set there, and the timestamps are less precise, hence
# --modify-window.
RSYNC_OPTS=(
    --recursive --links --times
    --no-perms --no-owner --no-group --omit-dir-times
    --modify-window=1
    --human-readable --itemize-changes
)

if [ "$DRY_RUN" -eq 1 ]; then
    RSYNC_OPTS+=( --dry-run )
    log "Dry run, nothing is written"
fi
if [ "$DELETE" -eq 1 ]; then
    RSYNC_OPTS+=( --delete )
    log "Deleting the windows side files that are gone here"
fi

for pattern in "${EXCLUDES[@]}"; do
    RSYNC_OPTS+=( --exclude "$pattern" )
done

command -v rsync >/dev/null 2>&1 || die "rsync not found on PATH"
[ -d "$DEST_ROOT" ] || die "windows workspace not found: $DEST_ROOT (is the partition mounted?)"

for project in "${PROJECTS[@]}"; do
    src="$SRC_ROOT/$project"
    dst="$DEST_ROOT/$project"
    [ -d "$src" ] || die "no such project: $src"
    [ -d "$dst" ] || die "no windows copy of $project: $dst (create it first)"
    log "$project: $src/ -> $dst/"
    rsync "${RSYNC_OPTS[@]}" "$src/" "$dst/"
done

log "Done. Run 'flutter pub get' on the windows side when the pubspec has changed."
